version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errorlint
  exclusions:
    rules:
      - linters: [ "errcheck" ]
        source: "^\\s*defer\\s+"
