name: test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Install dependencies
        run: go get .
      - name: Install cover
        run: go get golang.org/x/tools/cmd/cover
      - name: Build
        run: go build -v
      - name: Test with coverage
        run: go test -v -coverprofile cover.out
      - name: Generate coverage html output
        run: go tool cover -html cover.out -o cover.html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover.html
